apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-sample
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: dasmainak/react:5.0
        ports:
        - containerPort: 3000